name: Infection
main: me.KaliCode.infection.Main
version: 0.9
authors: [KaliCode]
description: An infection type mini-game for bukkit/spigot servers
commands:
  infection:
    description: Base command for the plugin
permissions:
  infection.admin:
    description: Permission to use /infection
